import Link from "next/link";
import { Wordmark } from "@/components/marketing/Wordmark";
import { marketingSamples } from "@/lib/marketing/samples";
import { SvgFrame } from "@/components/ui";

export const dynamic = "force-dynamic";

/**
 * Split layout for every auth screen: form on the left, live product output on
 * the right. The panel shows real generated brands, so the first thing someone
 * sees before signing up is the actual thing they are signing up for.
 */
export default function AuthLayout({ children }: { children: React.ReactNode }) {
  const samples = marketingSamples().slice(0, 4);

  return (
    <div className="min-h-screen grid lg:grid-cols-[minmax(0,1fr)_minmax(0,1.05fr)]">
      <div className="flex flex-col px-5 sm:px-10 py-8">
        <Wordmark />
        <div className="grow flex items-center justify-center py-10">
          <div className="w-full max-w-[380px] animate-in-up">{children}</div>
        </div>
        <p className="text-[12.5px] text-muted">
          <Link href="/terms" className="hover:text-ink transition-colors">
            Terms
          </Link>
          {" · "}
          <Link href="/privacy" className="hover:text-ink transition-colors">
            Privacy
          </Link>
        </p>
      </div>

      <aside className="hidden lg:flex flex-col justify-center bg-ink px-12 py-14 relative overflow-hidden">
        <div className="relative z-10 max-w-md">
          <h2 className="text-[30px] leading-[1.12] font-semibold text-white tracking-[-0.025em]">
            Every one of these was generated by the engine.
          </h2>
          <p className="mt-4 text-[15px] text-white/60 leading-relaxed">
            Not templates. Not stock. A complete brand system built from a few answers about the
            business.
          </p>

          <div className="mt-10 grid grid-cols-2 gap-4">
            {samples.map((sample) => (
              <div
                key={sample.name}
                className="bg-white rounded-[12px] p-5 flex flex-col items-center justify-center aspect-[4/3]"
              >
                <SvgFrame svg={sample.horizontal} className="w-full h-full" label={sample.name} />
              </div>
            ))}
          </div>
        </div>

        {/* Subtle brand texture, kept far behind the content. */}
        <div
          className="absolute inset-0 opacity-[0.05]"
          style={{
            backgroundImage:
              "radial-gradient(circle at 1px 1px, white 1px, transparent 0)",
            backgroundSize: "28px 28px",
          }}
          aria-hidden="true"
        />
      </aside>
    </div>
  );
}
