// GENERATED by scripts/gen-defaults.ts — do not edit.
// Run `npm run gen:defaults` after changing prisma/schema.prisma.

export type FieldDefault = { kind: "now" } | { kind: "value"; value: unknown };

/** @default(...) values per model, excluding generated ids. */
export const MODEL_DEFAULTS: Record<string, Record<string, FieldDefault>> = {
  "User": {
    "role": {
      "kind": "value",
      "value": "user"
    },
    "locale": {
      "kind": "value",
      "value": "en"
    },
    "createdAt": {
      "kind": "now"
    }
  },
  "Account": {
    "createdAt": {
      "kind": "now"
    }
  },
  "Session": {
    "createdAt": {
      "kind": "now"
    },
    "lastActiveAt": {
      "kind": "now"
    }
  },
  "VerificationToken": {
    "attempts": {
      "kind": "value",
      "value": 0
    },
    "createdAt": {
      "kind": "now"
    }
  },
  "Team": {
    "createdAt": {
      "kind": "now"
    }
  },
  "TeamMember": {
    "role": {
      "kind": "value",
      "value": "member"
    },
    "joinedAt": {
      "kind": "now"
    }
  },
  "Brand": {
    "language": {
      "kind": "value",
      "value": "en"
    },
    "status": {
      "kind": "value",
      "value": "draft"
    },
    "isPublic": {
      "kind": "value",
      "value": false
    },
    "viewCount": {
      "kind": "value",
      "value": 0
    },
    "createdAt": {
      "kind": "now"
    }
  },
  "BrandDirection": {
    "score": {
      "kind": "value",
      "value": 0
    },
    "isSelected": {
      "kind": "value",
      "value": false
    },
    "createdAt": {
      "kind": "now"
    }
  },
  "BrandIdentity": {
    "qualityScore": {
      "kind": "value",
      "value": 0
    },
    "version": {
      "kind": "value",
      "value": 1
    },
    "createdAt": {
      "kind": "now"
    }
  },
  "Logo": {
    "isPrimary": {
      "kind": "value",
      "value": false
    },
    "createdAt": {
      "kind": "now"
    }
  },
  "BrandAsset": {
    "createdAt": {
      "kind": "now"
    }
  },
  "Template": {
    "tier": {
      "kind": "value",
      "value": "free"
    },
    "sortOrder": {
      "kind": "value",
      "value": 0
    },
    "isActive": {
      "kind": "value",
      "value": true
    },
    "usageCount": {
      "kind": "value",
      "value": 0
    },
    "priceInr": {
      "kind": "value",
      "value": 0
    },
    "commissionBps": {
      "kind": "value",
      "value": 3000
    },
    "marketplaceState": {
      "kind": "value",
      "value": "first_party"
    },
    "createdAt": {
      "kind": "now"
    }
  },
  "AiGeneration": {
    "status": {
      "kind": "value",
      "value": "success"
    },
    "createdAt": {
      "kind": "now"
    }
  },
  "UsageRecord": {
    "count": {
      "kind": "value",
      "value": 0
    }
  },
  "Download": {
    "watermark": {
      "kind": "value",
      "value": false
    },
    "createdAt": {
      "kind": "now"
    }
  },
  "Plan": {
    "priceInr": {
      "kind": "value",
      "value": 0
    },
    "priceInrYear": {
      "kind": "value",
      "value": 0
    },
    "currency": {
      "kind": "value",
      "value": "INR"
    },
    "isActive": {
      "kind": "value",
      "value": true
    },
    "isPopular": {
      "kind": "value",
      "value": false
    },
    "sortOrder": {
      "kind": "value",
      "value": 0
    },
    "createdAt": {
      "kind": "now"
    }
  },
  "Subscription": {
    "status": {
      "kind": "value",
      "value": "active"
    },
    "currentPeriodStart": {
      "kind": "now"
    },
    "cancelAtPeriodEnd": {
      "kind": "value",
      "value": false
    },
    "createdAt": {
      "kind": "now"
    }
  },
  "Payment": {
    "currency": {
      "kind": "value",
      "value": "INR"
    },
    "createdAt": {
      "kind": "now"
    }
  },
  "Coupon": {
    "redemptions": {
      "kind": "value",
      "value": 0
    },
    "isActive": {
      "kind": "value",
      "value": true
    },
    "createdAt": {
      "kind": "now"
    }
  },
  "BlogPost": {
    "authorName": {
      "kind": "value",
      "value": "Chhaap"
    },
    "readMinutes": {
      "kind": "value",
      "value": 5
    },
    "isPublished": {
      "kind": "value",
      "value": false
    },
    "createdAt": {
      "kind": "now"
    }
  },
  "ShowcaseEntry": {
    "isFeatured": {
      "kind": "value",
      "value": false
    },
    "sortOrder": {
      "kind": "value",
      "value": 0
    },
    "createdAt": {
      "kind": "now"
    }
  },
  "RateLimit": {
    "count": {
      "kind": "value",
      "value": 0
    }
  }
};

/** Optional columns with no default; materialised as null. */
export const MODEL_NULLABLE: Record<string, string[]> = {
  "User": [
    "emailVerified",
    "name",
    "avatarUrl",
    "passwordHash",
    "lastSeenAt",
    "deletedAt",
    "subscription"
  ],
  "Account": [
    "accessToken",
    "refreshToken",
    "expiresAt"
  ],
  "Session": [
    "userAgent",
    "ip",
    "revokedAt"
  ],
  "VerificationToken": [
    "consumedAt"
  ],
  "Brand": [
    "teamId",
    "tagline",
    "audience",
    "colorPref",
    "scriptHint",
    "archivedAt",
    "identity"
  ],
  "BrandIdentity": [
    "qualityJson"
  ],
  "BrandAsset": [
    "templateId",
    "widthMm",
    "heightMm"
  ],
  "Template": [
    "description",
    "previewHint",
    "authorId"
  ],
  "AiGeneration": [
    "brandId",
    "model",
    "outputJson",
    "errorMessage",
    "latencyMs",
    "inputTokens",
    "outputTokens",
    "costMicroInr"
  ],
  "Download": [
    "detail"
  ],
  "Plan": [
    "description"
  ],
  "Subscription": [
    "gateway",
    "gatewaySubId",
    "currentPeriodEnd"
  ],
  "Payment": [
    "gatewayOrderId",
    "gatewayPayId",
    "signature",
    "couponCode",
    "metaJson"
  ],
  "Coupon": [
    "description",
    "percentOff",
    "amountOffInr",
    "maxRedemptions",
    "appliesToPlan",
    "expiresAt"
  ],
  "BlogPost": [
    "coverHint",
    "publishedAt",
    "seoTitle",
    "seoDesc"
  ],
  "ShowcaseEntry": [
    "approvedAt"
  ]
};
