import { generateDirections } from "@/lib/brand/engine";
import { buildLogoDocument, renderLogo } from "@/lib/render/logo";
import { renderAssetByKind } from "@/lib/render/assets/templates";
import { assetDefinition, withDefaults } from "@/lib/render/assets/definitions";
import { colorResolver } from "@/lib/render/svg";
import { scoreIdentity } from "@/lib/brand/quality";
import type { AssetData, AssetKind, BrandBrief } from "@/types/brand";

/**
 * Sample brands for the marketing pages.
 *
 * These are generated by the real engine at request time, not drawn by hand.
 * Every logo on the landing page is something the product would actually
 * produce for that brief — which is the only honest way to advertise it, and
 * doubles as a smoke test that anyone can see.
 */

export const SAMPLE_BRIEFS: BrandBrief[] = [
  {
    businessName: "Sharma Kirana",
    descriptor: "Provision & Daily Needs",
    industry: "kirana",
    audience: "families in the neighbourhood",
    personality: ["friendly", "trustworthy", "warm"],
    colorMood: "warm",
    language: "hi",
    localName: "शर्मा किराना",
    city: "Indore",
  },
  {
    businessName: "Aurelia",
    descriptor: "Fine Jewellery",
    industry: "jewellery",
    audience: "brides and gifting buyers",
    personality: ["premium", "traditional", "minimal"],
    colorMood: "jewel",
    language: "en",
    city: "Jaipur",
  },
  {
    businessName: "Kadak",
    descriptor: "Chai & Coffee",
    industry: "cafe",
    audience: "students and young professionals",
    personality: ["playful", "bold", "energetic"],
    colorMood: "vibrant",
    language: "hinglish",
    city: "Pune",
  },
  {
    businessName: "Thread & Loom",
    descriptor: "Handwoven Textiles",
    industry: "clothing",
    audience: "buyers who care where things come from",
    personality: ["handcrafted", "premium", "warm"],
    colorMood: "earthy",
    language: "en",
    city: "Bhuj",
  },
  {
    businessName: "Vaidya Clinic",
    descriptor: "Family Practice",
    industry: "healthcare",
    audience: "families needing a regular doctor",
    personality: ["trustworthy", "modern", "friendly"],
    colorMood: "cool",
    language: "mr",
    localName: "वैद्य क्लिनिक",
    city: "Nashik",
  },
  {
    businessName: "Meenakshi Silks",
    descriptor: "Kanchipuram Sarees",
    industry: "clothing",
    audience: "wedding and festival shoppers",
    personality: ["traditional", "premium", "warm"],
    colorMood: "jewel",
    language: "ta",
    localName: "மீனாட்சி சில்க்ஸ்",
    city: "Chennai",
  },
];

export interface Sample {
  name: string;
  descriptor: string;
  city: string;
  industry: string;
  language: string;
  logo: string;
  horizontal: string;
  icon: string;
  palette: { primary: string; accent: string; ink: string; surface: string };
  fonts: { display: string; body: string };
  tagline: string;
  score: number;
}

/**
 * Memoised because the engine is deterministic: the same briefs always produce
 * the same brands, so regenerating them per request is pure waste. This was
 * costing ~2.5s on every landing-page render — six briefs × four directions is
 * twenty-four complete brand systems, plus a full asset render.
 */
let cachedSamples: Sample[] | null = null;
let cachedShowcase: { key: string; value: AssetShowcase } | null = null;

/** One representative sample per brief. Deterministic, so it caches cleanly. */
export function marketingSamples(): Sample[] {
  return (cachedSamples ??= buildSamples());
}

function buildSamples(): Sample[] {
  return SAMPLE_BRIEFS.map((brief) => {
    const direction = generateDirections({ brief, count: 4 })[0]!;
    const spec = direction.spec;
    const quality = scoreIdentity(spec, buildLogoDocument(spec, "primary"));

    return {
      name: spec.name,
      descriptor: spec.descriptor ?? "",
      city: brief.city ?? "",
      industry: brief.industry,
      language: brief.language,
      logo: renderLogo({ doc: buildLogoDocument(spec, "vertical"), spec }),
      horizontal: renderLogo({ doc: buildLogoDocument(spec, "horizontal"), spec }),
      icon: renderLogo({ doc: buildLogoDocument(spec, "icon"), spec }),
      palette: {
        primary: spec.palette.primary.hex,
        accent: spec.palette.accent.hex,
        ink: spec.palette.ink.hex,
        surface: spec.palette.surface.hex,
      },
      fonts: { display: spec.typography.display.family, body: spec.typography.body.family },
      tagline: direction.strategy.taglines[0] ?? "",
      score: quality.score,
    };
  });
}

export interface AssetShowcase {
  name: string;
  items: { kind: AssetKind; label: string; svg: string; ratio: number }[];
}

/**
 * A single brand shown across many assets, for the "one system" section.
 * Cached per requested set — the landing page always asks for the same one.
 */
export function assetShowcase(kinds: AssetKind[]): AssetShowcase {
  const key = kinds.join(",");
  if (cachedShowcase?.key === key) return cachedShowcase.value;
  const value = renderShowcase(kinds);
  cachedShowcase = { key, value };
  return value;
}

function renderShowcase(kinds: AssetKind[]): AssetShowcase {
  const brief = SAMPLE_BRIEFS[2]!;
  const spec = generateDirections({ brief, count: 4 })[0]!.spec;
  const resolve = colorResolver(spec, "brand");

  return {
    name: spec.name,
    items: kinds.map((kind) => {
      const def = assetDefinition(kind);
      return {
        kind,
        label: def.name,
        svg: renderAssetByKind(kind, {
          spec,
          resolve,
          dim: def.dimension,
          data: withDefaults(kind, {}) as AssetData,
          watermark: false,
        }),
        ratio: def.dimension.width / def.dimension.height,
      };
    }),
  };
}
