import type { ColorMood, MarkStyle, PatternKind, PersonalityTrait } from "@/types/brand";
import type { AssetKind } from "@/types/brand";
import type { FontFeel } from "@/lib/fonts/catalog";

/**
 * The Indian business taxonomy.
 *
 * This is the platform's core proprietary data. Each entry encodes what a
 * category actually needs — which marks read correctly for it, which colours
 * its customers expect, which assets it will genuinely print, and the language
 * its owners use — so the generator produces something a kirana owner or a
 * jewellery house would recognise as theirs, not a generic startup logo.
 */

export interface IndustryProfile {
  key: string;
  name: string;
  /** Shown in the picker; deliberately uses the vocabulary owners use. */
  hint: string;
  group: IndustryGroup;
  /** Glyph library keys ranked best-first. */
  glyphs: string[];
  markStyles: { value: MarkStyle; weight: number }[];
  /** Colour moods that suit the category, best-first. */
  moods: ColorMood[];
  /** Hue windows (degrees) that perform well in this category. */
  hueWindows: [number, number][];
  personality: PersonalityTrait[];
  patterns: PatternKind[];
  /** Assets this category almost always needs, in priority order. */
  priorityAssets: AssetKind[];
  /** Category-flavoured tagline scaffolds; `{name}` and `{city}` interpolate. */
  taglineSeeds: string[];
  /** Words that make good brand-name components for this category. */
  nameRoots: string[];
  voiceHint: string;
  packagingHint: string;
  /** Typical descriptor line under the name in a lockup. */
  descriptorSeeds: string[];

  // --- typographic constraints -------------------------------------------
  // Filled in from GROUP_TYPE_DEFAULTS below unless an entry overrides them,
  // so the table stays readable instead of repeating the same three fields
  // thirty times.
  /** Type feels that flatter the category. */
  typeFeels?: FontFeel[];
  /** Type feels that misread for the category. */
  avoidFeels?: FontFeel[];
  /**
   * True when the business lives or dies by a physical board read from across
   * a road. Rules out delicate high-contrast faces at the pairing stage.
   */
  needsSignage?: boolean;
}

export type IndustryGroup =
  | "food"
  | "retail"
  | "beauty"
  | "fashion"
  | "services"
  | "professional"
  | "property"
  | "industry"
  | "creator";

export const INDUSTRY_GROUPS: { key: IndustryGroup; label: string }[] = [
  { key: "food", label: "Food & Beverage" },
  { key: "retail", label: "Retail & Kirana" },
  { key: "beauty", label: "Beauty & Wellness" },
  { key: "fashion", label: "Fashion & Jewellery" },
  { key: "services", label: "Local Services" },
  { key: "professional", label: "Professional & Agency" },
  { key: "property", label: "Real Estate" },
  { key: "industry", label: "Manufacturing & Trade" },
  { key: "creator", label: "Creators & Coaches" },
];

export const INDUSTRIES: IndustryProfile[] = [
  {
    key: "kirana",
    name: "Kirana / General Store",
    hint: "Neighbourhood provision store, supermarket, daily needs",
    group: "retail",
    glyphs: ["basket", "shop-front", "grain-sack", "scale", "bag"],
    markStyles: [
      { value: "glyph", weight: 5 },
      { value: "monogram", weight: 3 },
      { value: "abstract-stack", weight: 2 },
    ],
    moods: ["warm", "vibrant", "earthy"],
    hueWindows: [[10, 45], [95, 145], [200, 225]],
    personality: ["friendly", "trustworthy", "warm"],
    patterns: ["grid-dots", "chevron", "mark-tile"],
    priorityAssets: [
      "signboard",
      "visiting_card",
      "whatsapp_profile",
      "shopping_bag",
      "invoice",
      "poster",
    ],
    taglineSeeds: [
      "Everything your home needs",
      "Fresh stock, fair price",
      "Your daily needs, sorted",
      "Ghar ka saara saamaan",
      "Quality you can trust, daily",
    ],
    nameRoots: ["Bazaar", "Mart", "Stores", "Provision", "Daily", "Ghar", "Apna", "Suvidha"],
    voiceHint: "plain-spoken, neighbourly, price-and-stock led",
    packagingHint: "sturdy kraft carry bags with a bold single-colour mark",
    descriptorSeeds: ["General Store", "Provision & Daily Needs", "Since {year}", "Kirana Store"],
  },
  {
    key: "restaurant",
    name: "Restaurant",
    hint: "Dine-in, family restaurant, thali house, dhaba",
    group: "food",
    glyphs: ["thali", "flame", "spoon-fork", "chef-hat", "leaf-spice", "pot"],
    markStyles: [
      { value: "glyph", weight: 4 },
      { value: "monogram", weight: 4 },
      { value: "abstract-petal", weight: 2 },
    ],
    moods: ["warm", "jewel", "earthy"],
    hueWindows: [[0, 30], [25, 48], [340, 360]],
    personality: ["warm", "traditional", "premium"],
    patterns: ["arches", "lattice", "mark-tile"],
    priorityAssets: [
      "menu",
      "signboard",
      "instagram_post",
      "visiting_card",
      "poster",
      "packaging",
    ],
    taglineSeeds: [
      "Cooked the way it should be",
      "Taste that brings you back",
      "Ghar jaisa swaad",
      "Every plate, a promise",
      "Slow-cooked, freshly served",
    ],
    nameRoots: ["Rasoi", "Tadka", "Angan", "Darbar", "Zaika", "Bhoj", "Swaad", "Chulha"],
    voiceHint: "appetising and hospitable, leads with dishes not adjectives",
    packagingHint: "printed parcel boxes and sleeves in one hot colour on kraft",
    descriptorSeeds: ["Family Restaurant", "Pure Veg", "Since {year}", "Multi-Cuisine"],
  },
  {
    key: "cafe",
    name: "Cafe / Chai Shop",
    hint: "Coffee shop, chai tapri, bakery cafe, dessert bar",
    group: "food",
    glyphs: ["cup", "chai-glass", "bean", "croissant", "steam"],
    markStyles: [
      { value: "glyph", weight: 4 },
      { value: "monogram", weight: 3 },
      { value: "lettermark-cut", weight: 3 },
    ],
    moods: ["earthy", "warm", "pastel"],
    hueWindows: [[15, 40], [140, 165], [330, 355]],
    personality: ["friendly", "modern", "handcrafted"],
    patterns: ["grid-dots", "waves", "mark-tile"],
    priorityAssets: [
      "menu",
      "instagram_post",
      "signboard",
      "packaging",
      "visiting_card",
      "instagram_story",
    ],
    taglineSeeds: [
      "Brewed slow, served warm",
      "Your third place",
      "One more cup",
      "Chai, conversation, repeat",
      "Small batch, big comfort",
    ],
    nameRoots: ["Adda", "Tapri", "Brew", "Roast", "Chaupal", "Kettle", "Cup", "Baithak"],
    voiceHint: "relaxed and personal, second-person, low on exclamation marks",
    packagingHint: "matte cups and sleeves, mark stamped in one colour",
    descriptorSeeds: ["Coffee & Bakes", "Chai & Snacks", "Est. {year}", "Roastery"],
  },
  {
    key: "cloud_kitchen",
    name: "Cloud Kitchen / Tiffin",
    hint: "Delivery-only kitchen, tiffin service, home chef",
    group: "food",
    glyphs: ["tiffin", "pot", "flame", "leaf-spice", "spoon-fork"],
    markStyles: [
      { value: "glyph", weight: 4 },
      { value: "monogram", weight: 3 },
      { value: "abstract-orbit", weight: 2 },
    ],
    moods: ["vibrant", "warm"],
    hueWindows: [[0, 25], [30, 50], [100, 140]],
    personality: ["friendly", "energetic", "warm"],
    patterns: ["grid-dots", "chevron"],
    priorityAssets: [
      "instagram_post",
      "packaging",
      "whatsapp_profile",
      "menu",
      "flyer",
      "product_label",
    ],
    taglineSeeds: [
      "Home food, delivered hot",
      "Cooked fresh, every order",
      "Ghar ka khana, roz",
      "Real food, real fast",
    ],
    nameRoots: ["Dabba", "Tiffin", "Rasoi", "Daily", "Fresh", "Ghar", "Thali"],
    voiceHint: "practical and warm, menu-and-timing led",
    packagingHint: "food-grade containers with a sticker label system",
    descriptorSeeds: ["Home Kitchen", "Tiffin Service", "Delivery Only"],
  },
  {
    key: "salon",
    name: "Salon & Spa",
    hint: "Hair salon, beauty parlour, spa, barbershop",
    group: "beauty",
    glyphs: ["scissors", "comb", "lotus", "mirror", "razor", "petal"],
    markStyles: [
      { value: "monogram", weight: 4 },
      { value: "glyph", weight: 3 },
      { value: "abstract-petal", weight: 3 },
    ],
    moods: ["jewel", "pastel", "monochrome"],
    hueWindows: [[275, 320], [330, 355], [160, 190]],
    personality: ["premium", "modern", "warm"],
    patterns: ["concentric", "lattice", "diagonal-stripes"],
    priorityAssets: [
      "signboard",
      "instagram_post",
      "visiting_card",
      "poster",
      "instagram_story",
      "menu",
    ],
    taglineSeeds: [
      "Look like yourself, only better",
      "Care that shows",
      "Your chair is ready",
      "Style, unhurried",
    ],
    nameRoots: ["Glow", "Studio", "Salon", "Roop", "Shringar", "Bloom", "Kanti", "Mirror"],
    voiceHint: "confident and caring, never body-critical",
    packagingHint: "soft-touch boxes for retail products, foil-look mark",
    descriptorSeeds: ["Hair & Beauty", "Unisex Salon", "Salon & Spa", "Est. {year}"],
  },
  {
    key: "clothing",
    name: "Clothing Brand",
    hint: "Apparel label, boutique, saree house, streetwear",
    group: "fashion",
    glyphs: ["thread", "hanger", "fold", "button", "loom"],
    markStyles: [
      { value: "monogram", weight: 5 },
      { value: "lettermark-cut", weight: 3 },
      { value: "wordmark-only", weight: 3 },
    ],
    moods: ["monochrome", "jewel", "earthy"],
    hueWindows: [[0, 20], [200, 240], [20, 40]],
    personality: ["premium", "minimal", "modern"],
    patterns: ["diagonal-stripes", "lattice", "mark-tile"],
    priorityAssets: [
      "instagram_post",
      "product_label",
      "shopping_bag",
      "visiting_card",
      "tshirt",
      "instagram_story",
    ],
    taglineSeeds: [
      "Made to be worn, not stored",
      "Cloth with a memory",
      "Everyday, elevated",
      "Cut for real life",
    ],
    nameRoots: ["Kapda", "Vastra", "Loom", "Thread", "Weave", "Taana", "Baana", "Studio"],
    voiceHint: "understated and tactile, talks about fabric and fit",
    packagingHint: "cotton bags and hang tags, mark blind-embossed or single-colour",
    descriptorSeeds: ["Clothing", "Apparel Co.", "Handloom", "Est. {year}"],
  },
  {
    key: "jewellery",
    name: "Jewellery Brand",
    hint: "Gold, silver, artificial jewellery, showroom",
    group: "fashion",
    glyphs: ["gem", "necklace", "lotus", "sun-rays", "ring"],
    markStyles: [
      { value: "monogram", weight: 5 },
      { value: "glyph", weight: 3 },
      { value: "abstract-petal", weight: 2 },
    ],
    moods: ["jewel", "monochrome"],
    hueWindows: [[35, 50], [0, 15], [255, 285]],
    personality: ["premium", "traditional", "trustworthy"],
    patterns: ["concentric", "lattice", "arches"],
    priorityAssets: [
      "visiting_card",
      "signboard",
      "instagram_post",
      "packaging",
      "letterhead",
      "poster",
    ],
    taglineSeeds: [
      "Kept for generations",
      "Weight you can trust",
      "Craft that outlives trend",
      "Hallmarked, always",
    ],
    nameRoots: ["Swarna", "Ratna", "Jewels", "Kalash", "Heera", "Aabharan", "Sona"],
    voiceHint: "assured and heritage-leaning, purity and craft over discounts",
    packagingHint: "rigid boxes with pouch inserts, foil-stamped mark",
    descriptorSeeds: ["Jewellers", "Fine Jewellery", "Since {year}", "Gold & Diamonds"],
  },
  {
    key: "footwear",
    name: "Footwear Brand",
    hint: "Shoes, sandals, sneakers, mochi/repair",
    group: "fashion",
    glyphs: ["shoe", "sole", "lace", "step", "thread"],
    markStyles: [
      { value: "lettermark-cut", weight: 4 },
      { value: "monogram", weight: 4 },
      { value: "abstract-stack", weight: 2 },
    ],
    moods: ["monochrome", "earthy", "vibrant"],
    hueWindows: [[0, 20], [20, 40], [210, 245]],
    personality: ["bold", "modern", "handcrafted"],
    patterns: ["diagonal-stripes", "chevron", "mark-tile"],
    priorityAssets: [
      "instagram_post",
      "packaging",
      "product_label",
      "shopping_bag",
      "visiting_card",
      "poster",
    ],
    taglineSeeds: [
      "Built for the long walk",
      "Every step, held",
      "Made to be worn out",
      "Comfort, mile after mile",
    ],
    nameRoots: ["Step", "Chaal", "Sole", "Pace", "Mochi", "Charan", "Stride"],
    voiceHint: "direct and durable-sounding, comfort and craft first",
    packagingHint: "printed shoe boxes with a repeating mark tile inside the lid",
    descriptorSeeds: ["Footwear", "Handcrafted Shoes", "Est. {year}"],
  },
  {
    key: "d2c",
    name: "D2C Brand",
    hint: "Direct-to-consumer product brand, wellness, home, packaged goods",
    group: "retail",
    glyphs: ["leaf-spice", "bottle", "jar", "drop", "sprout", "box"],
    markStyles: [
      { value: "abstract-petal", weight: 3 },
      { value: "monogram", weight: 3 },
      { value: "glyph", weight: 4 },
    ],
    moods: ["pastel", "earthy", "vibrant"],
    hueWindows: [[100, 150], [25, 45], [170, 200]],
    personality: ["modern", "friendly", "minimal"],
    patterns: ["grid-dots", "waves", "mark-tile"],
    priorityAssets: [
      "product_label",
      "packaging",
      "instagram_post",
      "website_hero",
      "shopping_bag",
      "instagram_story",
    ],
    taglineSeeds: [
      "Made small, made well",
      "Nothing you can't pronounce",
      "Straight from source",
      "Better basics",
    ],
    nameRoots: ["Nature", "Pure", "Shuddh", "Origin", "Roots", "Amrit", "Bhoomi", "Sattva"],
    voiceHint: "ingredient-honest and calm, avoids miracle claims",
    packagingHint: "label-led system with a consistent panel grid across SKUs",
    descriptorSeeds: ["{city}", "Small Batch", "Est. {year}", "Made in India"],
  },
  {
    key: "realestate",
    name: "Real Estate",
    hint: "Builder, broker, property consultant, interiors",
    group: "property",
    glyphs: ["house", "building", "key", "arch-door", "pillar"],
    markStyles: [
      { value: "glyph", weight: 4 },
      { value: "monogram", weight: 4 },
      { value: "abstract-stack", weight: 3 },
    ],
    moods: ["cool", "monochrome", "jewel"],
    hueWindows: [[200, 235], [35, 48], [155, 180]],
    personality: ["trustworthy", "premium", "modern"],
    patterns: ["lattice", "grid-dots", "concentric"],
    priorityAssets: [
      "visiting_card",
      "letterhead",
      "signboard",
      "brochure",
      "linkedin_banner",
      "poster",
    ],
    taglineSeeds: [
      "Addresses worth keeping",
      "Built on paperwork you can read",
      "Where the city is going next",
      "Property, without the runaround",
    ],
    nameRoots: ["Griha", "Nivas", "Estate", "Bhoomi", "Realty", "Aangan", "Sthal", "Vastu"],
    voiceHint: "precise and reassuring, specifics over superlatives",
    packagingHint: "presentation folders and site brochures on uncoated stock",
    descriptorSeeds: ["Realty", "Property Consultants", "Builders & Developers", "Since {year}"],
  },
  {
    key: "agency",
    name: "Agency / Studio",
    hint: "Marketing, design, IT services, consulting",
    group: "professional",
    glyphs: ["spark", "node", "prism", "arrow-up", "layers"],
    markStyles: [
      { value: "abstract-orbit", weight: 4 },
      { value: "lettermark-cut", weight: 3 },
      { value: "monogram", weight: 3 },
    ],
    moods: ["cool", "monochrome", "vibrant"],
    hueWindows: [[220, 265], [265, 300], [0, 15]],
    personality: ["modern", "bold", "technical"],
    patterns: ["grid-dots", "diagonal-stripes", "concentric"],
    priorityAssets: [
      "linkedin_banner",
      "letterhead",
      "visiting_card",
      "website_hero",
      "invoice",
      "brochure",
    ],
    taglineSeeds: [
      "Work that ships",
      "Fewer decks, more outcomes",
      "Built to be measured",
      "Strategy you can act on",
    ],
    nameRoots: ["Labs", "Works", "Studio", "Collective", "Forge", "Yantra", "Kaarya", "Nexus"],
    voiceHint: "sharp and specific, claims backed by numbers",
    packagingHint: "not applicable — invest in deck and document templates instead",
    descriptorSeeds: ["Studio", "Consulting", "Digital Agency", "Est. {year}"],
  },
  {
    key: "freelancer",
    name: "Freelancer",
    hint: "Solo designer, developer, photographer, writer",
    group: "creator",
    glyphs: ["pen", "camera", "cursor", "spark", "quill"],
    markStyles: [
      { value: "monogram", weight: 5 },
      { value: "lettermark-cut", weight: 3 },
      { value: "wordmark-only", weight: 2 },
    ],
    moods: ["monochrome", "cool", "vibrant"],
    hueWindows: [[0, 20], [240, 275], [155, 180]],
    personality: ["minimal", "modern", "handcrafted"],
    patterns: ["grid-dots", "diagonal-stripes"],
    priorityAssets: [
      "visiting_card",
      "invoice",
      "linkedin_banner",
      "instagram_profile",
      "letterhead",
      "website_hero",
    ],
    taglineSeeds: [
      "One person, all in",
      "Small studio, sharp work",
      "Available for select projects",
      "Design that earns its keep",
    ],
    nameRoots: ["Studio", "Works", "Co.", "Craft", "Atelier", "Kalam", "Chitra"],
    voiceHint: "first-person and candid, portfolio-led",
    packagingHint: "not applicable — focus on invoice and proposal templates",
    descriptorSeeds: ["Design Studio", "Photography", "Independent", "{city}"],
  },
  {
    key: "coach",
    name: "Coach / Educator",
    hint: "Tuition, coaching class, fitness trainer, online course",
    group: "creator",
    glyphs: ["book", "lamp", "sprout", "arrow-up", "compass"],
    markStyles: [
      { value: "glyph", weight: 4 },
      { value: "monogram", weight: 4 },
      { value: "abstract-orbit", weight: 2 },
    ],
    moods: ["cool", "vibrant", "warm"],
    hueWindows: [[205, 240], [15, 40], [140, 170]],
    personality: ["trustworthy", "energetic", "friendly"],
    patterns: ["concentric", "grid-dots", "chevron"],
    priorityAssets: [
      "instagram_post",
      "poster",
      "visiting_card",
      "youtube_banner",
      "flyer",
      "whatsapp_profile",
    ],
    taglineSeeds: [
      "Results you can measure",
      "Learn it once, properly",
      "Small batches, full attention",
      "Progress, every week",
    ],
    nameRoots: ["Vidya", "Gurukul", "Path", "Academy", "Shiksha", "Uday", "Prayas", "Disha"],
    voiceHint: "encouraging and concrete, outcomes and schedules up front",
    packagingHint: "not applicable — invest in worksheets and certificate templates",
    descriptorSeeds: ["Coaching Classes", "Academy", "Since {year}", "{city}"],
  },
  {
    key: "local_service",
    name: "Local Service",
    hint: "Electrician, plumber, packers & movers, laundry, repairs",
    group: "services",
    glyphs: ["wrench", "bolt", "truck", "drop", "gear", "brush"],
    markStyles: [
      { value: "glyph", weight: 5 },
      { value: "monogram", weight: 3 },
      { value: "abstract-stack", weight: 1 },
    ],
    moods: ["vibrant", "cool"],
    hueWindows: [[205, 235], [35, 50], [0, 20]],
    personality: ["trustworthy", "friendly", "bold"],
    patterns: ["chevron", "diagonal-stripes", "grid-dots"],
    priorityAssets: [
      "visiting_card",
      "signboard",
      "flyer",
      "whatsapp_profile",
      "invoice",
      "poster",
    ],
    taglineSeeds: [
      "On time, every time",
      "Call once, fixed once",
      "Same-day service",
      "Honest work, fair rate",
    ],
    nameRoots: ["Seva", "Fix", "Care", "Sahayak", "Quick", "Sudhaar", "Bandhu"],
    voiceHint: "practical and reassuring, leads with response time and phone number",
    packagingHint: "not applicable — put the mark on van livery and uniforms",
    descriptorSeeds: ["Services", "Repairs & Service", "{city}", "24×7"],
  },
  {
    key: "startup",
    name: "Startup",
    hint: "App, SaaS, fintech, marketplace",
    group: "professional",
    glyphs: ["spark", "node", "arrow-up", "prism", "shield", "layers"],
    markStyles: [
      { value: "abstract-orbit", weight: 4 },
      { value: "abstract-stack", weight: 3 },
      { value: "lettermark-cut", weight: 3 },
    ],
    moods: ["cool", "vibrant"],
    hueWindows: [[225, 270], [155, 180], [270, 300]],
    personality: ["modern", "technical", "bold"],
    patterns: ["grid-dots", "concentric", "waves"],
    priorityAssets: [
      "website_hero",
      "linkedin_banner",
      "instagram_post",
      "visiting_card",
      "letterhead",
      "instagram_profile",
    ],
    taglineSeeds: [
      "The simple way to {verb}",
      "Built for how India actually works",
      "Less process, more progress",
      "Made for the next hundred million",
    ],
    nameRoots: ["Setu", "Yatra", "Kosh", "Flow", "Lekha", "Udaan", "Kite", "Arc"],
    voiceHint: "clear and unhyped, explains the job to be done in one line",
    packagingHint: "not applicable — focus on app icon and store assets",
    descriptorSeeds: ["Technologies", "Labs", "{city}", "Est. {year}"],
  },
  {
    key: "manufacturer",
    name: "Manufacturer / Trader",
    hint: "Factory, wholesale, exports, B2B supply",
    group: "industry",
    glyphs: ["gear", "factory", "box", "shield", "pillar", "scale"],
    markStyles: [
      { value: "monogram", weight: 4 },
      { value: "glyph", weight: 4 },
      { value: "abstract-stack", weight: 2 },
    ],
    moods: ["cool", "monochrome", "earthy"],
    hueWindows: [[205, 235], [0, 18], [30, 45]],
    personality: ["trustworthy", "bold", "technical"],
    patterns: ["chevron", "lattice", "diagonal-stripes"],
    priorityAssets: [
      "letterhead",
      "visiting_card",
      "invoice",
      "brochure",
      "packaging",
      "signboard",
    ],
    taglineSeeds: [
      "Supplying since {year}",
      "Specification, met",
      "Volume without variance",
      "Built to tolerance",
    ],
    nameRoots: ["Udyog", "Industries", "Works", "Enterprises", "Nirman", "Shakti", "Bharat"],
    voiceHint: "specification-led and formal, certifications and capacity up front",
    packagingHint: "master cartons with stencil-style marks and clear grade panels",
    descriptorSeeds: ["Industries", "Enterprises", "Est. {year}", "Manufacturers & Exporters"],
  },
  {
    key: "healthcare",
    name: "Clinic / Healthcare",
    hint: "Doctor, dental, diagnostics, pharmacy, wellness",
    group: "services",
    glyphs: ["pulse", "cross-care", "lotus", "shield", "drop"],
    markStyles: [
      { value: "glyph", weight: 5 },
      { value: "monogram", weight: 3 },
      { value: "abstract-petal", weight: 2 },
    ],
    moods: ["cool", "pastel"],
    hueWindows: [[160, 195], [200, 225], [140, 165]],
    personality: ["trustworthy", "warm", "minimal"],
    patterns: ["concentric", "grid-dots"],
    priorityAssets: [
      "visiting_card",
      "letterhead",
      "signboard",
      "invoice",
      "poster",
      "whatsapp_profile",
    ],
    taglineSeeds: [
      "Care that listens",
      "Right diagnosis, first",
      "Health, close to home",
      "Appointments that run on time",
    ],
    nameRoots: ["Arogya", "Swasthya", "Care", "Jeevan", "Nirog", "Sanjivani", "Ayu"],
    voiceHint: "calm and plain, never over-promises outcomes",
    packagingHint: "not applicable — prioritise prescription pads and signage",
    descriptorSeeds: ["Clinic", "Multi-Speciality", "Diagnostics", "Since {year}"],
  },

  // --- added: the categories a real Indian high street actually contains ----
  {
    key: "sweets",
    name: "Sweet Shop / Mithai",
    hint: "Mithai, namkeen, festival boxes, dry fruits",
    group: "food",
    glyphs: ["cake", "thali", "jar", "flame", "lotus"],
    markStyles: [{ value: "glyph", weight: 5 }, { value: "monogram", weight: 3 }],
    moods: ["warm", "jewel", "vibrant"],
    hueWindows: [[8, 45], [340, 360]],
    personality: ["traditional", "warm", "premium"],
    patterns: ["arches", "lattice", "concentric"],
    priorityAssets: ["signboard", "packaging", "visiting_card", "shopping_bag", "poster"],
    taglineSeeds: ["Taste that stays in the family", "Fresh every morning, since always", "Mithai jaisi maa banati hai", "Festive since {year}"],
    nameRoots: ["Sweets", "Mithai", "Bhandar", "Namkeen", "Misthan"],
    voiceHint: "warm, festive, family-led",
    packagingHint: "gift boxes with a gold-foil mark and a deep base colour",
    descriptorSeeds: ["Sweets & Namkeen", "Since {year}", "Mithai & Dry Fruits"],
  },
  {
    key: "bakery",
    name: "Bakery",
    hint: "Bread, cakes, pastries, birthday orders",
    group: "food",
    glyphs: ["croissant", "cake", "chef-hat", "flame"],
    markStyles: [{ value: "glyph", weight: 5 }, { value: "monogram", weight: 2 }],
    moods: ["warm", "pastel", "earthy"],
    hueWindows: [[18, 48], [330, 355]],
    personality: ["warm", "friendly", "handcrafted"],
    patterns: ["grid-dots", "waves", "arches"],
    priorityAssets: ["signboard", "packaging", "instagram_post", "visiting_card", "product_label"],
    taglineSeeds: ["Out of the oven at six", "Baked, not bought", "Fresh bread, every single day"],
    nameRoots: ["Bakery", "Bake House", "Oven", "Crumb", "Patisserie"],
    voiceHint: "homely, sensory, morning-led",
    packagingHint: "kraft boxes and paper bags with a one-colour stamp",
    descriptorSeeds: ["Bakery & Patisserie", "Artisan Bakery", "Since {year}"],
  },
  {
    key: "catering",
    name: "Catering & Tiffin Service",
    hint: "Bulk orders, weddings, office tiffin",
    group: "food",
    glyphs: ["tiffin", "thali", "spoon-fork", "chef-hat", "pot"],
    markStyles: [{ value: "glyph", weight: 4 }, { value: "monogram", weight: 3 }],
    moods: ["warm", "earthy", "vibrant"],
    hueWindows: [[10, 45], [100, 150]],
    personality: ["trustworthy", "warm", "friendly"],
    patterns: ["mark-tile", "chevron", "grid-dots"],
    priorityAssets: ["visiting_card", "whatsapp_profile", "menu", "flyer", "invoice"],
    taglineSeeds: ["Ghar ka khana, roz", "Fifty plates or five hundred", "On time, every time"],
    nameRoots: ["Caterers", "Kitchen", "Tiffin", "Rasoi", "Bhojan"],
    voiceHint: "dependable, quantity-and-timing led",
    packagingHint: "stackable containers with a bold single-colour label",
    descriptorSeeds: ["Catering & Tiffin", "Pure Veg Catering", "Since {year}"],
  },
  {
    key: "dairy",
    name: "Dairy & Milk Products",
    hint: "Milk, paneer, ghee, curd",
    group: "food",
    glyphs: ["milk-can", "bottle", "drop", "sprout"],
    markStyles: [{ value: "glyph", weight: 5 }, { value: "monogram", weight: 2 }],
    moods: ["cool", "pastel", "earthy"],
    hueWindows: [[100, 160], [190, 225]],
    personality: ["trustworthy", "friendly", "traditional"],
    patterns: ["waves", "grid-dots", "concentric"],
    priorityAssets: ["product_label", "signboard", "packaging", "visiting_card"],
    taglineSeeds: ["Straight from the farm", "Pure, every single day", "Doodh jaisa doodh"],
    nameRoots: ["Dairy", "Doodh", "Amrit", "Gau", "Farm"],
    voiceHint: "plain, purity-and-freshness led",
    packagingHint: "clean white pouches and bottles with one strong accent",
    descriptorSeeds: ["Dairy & Milk Products", "Fresh Dairy", "Since {year}"],
  },

  {
    key: "pharmacy",
    name: "Pharmacy / Medical Store",
    hint: "Chemist, medicines, health supplies",
    group: "services",
    glyphs: ["capsule", "cross-care", "mortar", "pulse"],
    markStyles: [{ value: "glyph", weight: 5 }, { value: "monogram", weight: 3 }],
    moods: ["cool", "monochrome"],
    hueWindows: [[150, 210], [200, 240]],
    personality: ["trustworthy", "modern", "technical"],
    patterns: ["grid-dots", "chevron", "lattice"],
    priorityAssets: ["signboard", "visiting_card", "invoice", "whatsapp_profile"],
    taglineSeeds: ["Open when you need us", "Genuine medicines, fair price", "Aapki sehat, hamari zimmedari"],
    nameRoots: ["Medicals", "Pharmacy", "Chemist", "Health", "Care"],
    voiceHint: "calm, precise, availability-led",
    packagingHint: "plain carry bags with a clear cross or capsule mark",
    descriptorSeeds: ["Chemist & Druggist", "Pharmacy", "Since {year}"],
  },
  {
    key: "dental",
    name: "Dental Clinic",
    hint: "Dentist, orthodontics, implants",
    group: "services",
    glyphs: ["tooth", "cross-care", "spark", "pulse"],
    markStyles: [{ value: "glyph", weight: 4 }, { value: "monogram", weight: 4 }],
    moods: ["cool", "pastel", "monochrome"],
    hueWindows: [[175, 230]],
    personality: ["trustworthy", "modern", "minimal"],
    patterns: ["grid-dots", "concentric"],
    priorityAssets: ["signboard", "visiting_card", "letterhead", "instagram_post"],
    taglineSeeds: ["Painless, honestly", "Smiles that last", "Modern dentistry, gentle hands"],
    nameRoots: ["Dental", "Smile", "Dent", "Oral", "Care"],
    voiceHint: "reassuring, jargon-free, gentle",
    packagingHint: "clean white with one calm accent",
    descriptorSeeds: ["Dental Clinic", "Dental Care & Implants", "Since {year}"],
  },
  {
    key: "gym",
    name: "Gym & Fitness",
    hint: "Gym, CrossFit, yoga studio, personal training",
    group: "services",
    glyphs: ["dumbbell", "pulse", "bolt", "arrow-up", "lotus"],
    markStyles: [{ value: "lettermark-cut", weight: 4 }, { value: "glyph", weight: 4 }, { value: "abstract-stack", weight: 2 }],
    moods: ["vibrant", "monochrome", "cool"],
    hueWindows: [[0, 30], [190, 230], [80, 110]],
    personality: ["bold", "energetic", "modern"],
    patterns: ["diagonal-stripes", "chevron", "grid-dots"],
    priorityAssets: ["signboard", "instagram_post", "tshirt", "poster", "visiting_card"],
    taglineSeeds: ["Show up. That's it.", "Stronger than yesterday", "No excuses, only reps"],
    nameRoots: ["Fitness", "Gym", "Strength", "Iron", "Akhada"],
    voiceHint: "direct, motivating, no fluff",
    packagingHint: "bold one-colour prints on tees, bottles and bands",
    descriptorSeeds: ["Fitness Studio", "Gym & Personal Training", "Since {year}"],
  },
  {
    key: "optical",
    name: "Optical / Eyewear",
    hint: "Spectacles, lenses, eye testing",
    group: "retail",
    glyphs: ["glasses", "cross-care", "spark"],
    markStyles: [{ value: "glyph", weight: 5 }, { value: "monogram", weight: 3 }],
    moods: ["cool", "monochrome", "jewel"],
    hueWindows: [[195, 260], [0, 360]],
    personality: ["modern", "premium", "trustworthy"],
    patterns: ["concentric", "grid-dots"],
    priorityAssets: ["signboard", "visiting_card", "instagram_post", "shopping_bag"],
    taglineSeeds: ["See it properly", "Frames that fit your face", "Eye tests, free"],
    nameRoots: ["Opticals", "Vision", "Optics", "Eye", "Lens"],
    voiceHint: "precise, service-led, unfussy",
    packagingHint: "slim cases and cloth pouches with a debossed mark",
    descriptorSeeds: ["Opticals", "Eyewear & Eye Care", "Since {year}"],
  },
  {
    key: "pet",
    name: "Pet Care & Veterinary",
    hint: "Vet clinic, pet shop, grooming, boarding",
    group: "services",
    glyphs: ["paw", "cross-care", "drop", "sprout"],
    markStyles: [{ value: "glyph", weight: 5 }, { value: "abstract-petal", weight: 2 }],
    moods: ["warm", "pastel", "vibrant"],
    hueWindows: [[20, 50], [150, 200]],
    personality: ["friendly", "warm", "trustworthy"],
    patterns: ["grid-dots", "mark-tile", "waves"],
    priorityAssets: ["signboard", "visiting_card", "instagram_post", "whatsapp_profile"],
    taglineSeeds: ["Because they're family", "Gentle hands, happy tails", "Open on Sundays too"],
    nameRoots: ["Pets", "Paws", "Vet", "Care", "Tails"],
    voiceHint: "affectionate, reassuring, owner-to-owner",
    packagingHint: "soft colours with a friendly rounded mark",
    descriptorSeeds: ["Pet Clinic & Store", "Veterinary Care", "Since {year}"],
  },

  {
    key: "education",
    name: "Coaching & Tuition",
    hint: "Coaching classes, tuition, test prep, school",
    group: "professional",
    glyphs: ["mortarboard", "book", "step", "spark", "pen"],
    markStyles: [{ value: "glyph", weight: 4 }, { value: "monogram", weight: 4 }, { value: "abstract-stack", weight: 2 }],
    moods: ["cool", "vibrant", "monochrome"],
    hueWindows: [[200, 250], [10, 40]],
    personality: ["trustworthy", "modern", "technical"],
    patterns: ["grid-dots", "chevron", "lattice"],
    priorityAssets: ["signboard", "flyer", "visiting_card", "poster", "instagram_post"],
    taglineSeeds: ["Results, not promises", "Concepts first, marks follow", "Small batches, full attention"],
    nameRoots: ["Academy", "Classes", "Institute", "Vidya", "Gurukul", "Coaching"],
    voiceHint: "confident, results-and-method led",
    packagingHint: "printed notes and folders with a clear institutional mark",
    descriptorSeeds: ["Coaching Institute", "Tuition Classes", "Since {year}"],
  },
  {
    key: "finance",
    name: "Finance, CA & Insurance",
    hint: "Chartered accountant, tax, insurance, loans",
    group: "professional",
    glyphs: ["chart", "briefcase", "pillar", "shield", "arrow-up"],
    markStyles: [{ value: "monogram", weight: 4 }, { value: "abstract-stack", weight: 3 }, { value: "glyph", weight: 2 }],
    moods: ["cool", "monochrome", "jewel"],
    hueWindows: [[200, 250], [150, 185]],
    personality: ["trustworthy", "premium", "technical"],
    patterns: ["grid-dots", "lattice", "chevron"],
    priorityAssets: ["letterhead", "visiting_card", "invoice", "linkedin_banner"],
    taglineSeeds: ["Numbers you can rely on", "Filed right, filed on time", "Your money, handled carefully"],
    nameRoots: ["Associates", "Advisors", "Capital", "Finserv", "Consultancy"],
    voiceHint: "measured, precise, compliance-aware",
    packagingHint: "restrained stationery; a foil-blocked mark on folders",
    descriptorSeeds: ["Chartered Accountants", "Financial Advisors", "Since {year}"],
  },
  {
    key: "legal",
    name: "Legal Services",
    hint: "Advocate, law firm, notary, documentation",
    group: "professional",
    glyphs: ["pillar", "scale", "quill", "briefcase", "shield"],
    markStyles: [{ value: "monogram", weight: 5 }, { value: "glyph", weight: 3 }],
    moods: ["monochrome", "jewel", "cool"],
    hueWindows: [[200, 250], [340, 360]],
    personality: ["trustworthy", "traditional", "premium"],
    patterns: ["lattice", "concentric", "grid-dots"],
    priorityAssets: ["letterhead", "visiting_card", "invoice"],
    taglineSeeds: ["Counsel you can trust", "Practising since {year}", "Clear advice, plainly given"],
    nameRoots: ["& Associates", "Law", "Legal", "Chambers", "Advocates"],
    voiceHint: "formal, precise, unshowy",
    packagingHint: "heavyweight stationery, blind-embossed mark, no colour",
    descriptorSeeds: ["Advocates & Legal Consultants", "Law Chambers", "Since {year}"],
  },
  {
    key: "it_services",
    name: "IT & Software Services",
    hint: "Software company, web development, IT support",
    group: "professional",
    glyphs: ["node", "layers", "cursor", "prism", "globe"],
    markStyles: [{ value: "abstract-stack", weight: 4 }, { value: "abstract-orbit", weight: 3 }, { value: "lettermark-cut", weight: 3 }],
    moods: ["cool", "monochrome", "vibrant"],
    hueWindows: [[200, 265], [160, 190]],
    personality: ["technical", "modern", "minimal"],
    patterns: ["grid-dots", "diagonal-stripes", "lattice"],
    priorityAssets: ["website_hero", "linkedin_banner", "visiting_card", "letterhead"],
    taglineSeeds: ["Built to scale", "Software that ships", "Engineering, not guesswork"],
    nameRoots: ["Technologies", "Systems", "Labs", "Software", "Digital"],
    voiceHint: "precise, capability-led, no hype",
    packagingHint: "minimal digital-first collateral",
    descriptorSeeds: ["Software Solutions", "IT Services", "Technology Partners"],
  },
  {
    key: "photography",
    name: "Photography & Video",
    hint: "Wedding photography, studio, videography",
    group: "creator",
    glyphs: ["camera", "prism", "spark", "sun-rays"],
    markStyles: [{ value: "glyph", weight: 4 }, { value: "monogram", weight: 4 }, { value: "lettermark-cut", weight: 2 }],
    moods: ["monochrome", "earthy", "jewel"],
    hueWindows: [[0, 360]],
    personality: ["premium", "minimal", "modern"],
    patterns: ["grid-dots", "concentric"],
    priorityAssets: ["instagram_profile", "instagram_post", "visiting_card", "website_hero"],
    taglineSeeds: ["Moments, kept properly", "Your day, remembered right", "Light, patience, timing"],
    nameRoots: ["Studios", "Films", "Frames", "Photography", "Lens"],
    voiceHint: "quiet, image-led, few words",
    packagingHint: "matte album boxes with a blind-debossed mark",
    descriptorSeeds: ["Photography & Films", "Wedding Photography", "Studio"],
  },
  {
    key: "events",
    name: "Events & Wedding Planning",
    hint: "Wedding planner, event management, decor",
    group: "creator",
    glyphs: ["calendar-star", "spark", "lotus", "petal", "ring"],
    markStyles: [{ value: "glyph", weight: 3 }, { value: "monogram", weight: 4 }, { value: "abstract-petal", weight: 3 }],
    moods: ["jewel", "pastel", "vibrant"],
    hueWindows: [[330, 360], [250, 290], [30, 50]],
    personality: ["premium", "warm", "playful"],
    patterns: ["arches", "concentric", "lattice"],
    priorityAssets: ["instagram_post", "visiting_card", "brochure", "website_hero"],
    taglineSeeds: ["Your day, handled", "Every detail, on time", "Celebrations, planned properly"],
    nameRoots: ["Events", "Weddings", "Occasions", "Utsav", "Planners"],
    voiceHint: "warm, reassuring, detail-led",
    packagingHint: "invitation-grade paper with foil and a fine mark",
    descriptorSeeds: ["Event & Wedding Planners", "Events & Decor", "Since {year}"],
  },
  {
    key: "travel",
    name: "Travel & Tourism",
    hint: "Travel agency, tour operator, cab service",
    group: "services",
    glyphs: ["suitcase", "compass", "globe", "car", "sun-rays"],
    markStyles: [{ value: "glyph", weight: 4 }, { value: "abstract-orbit", weight: 3 }, { value: "monogram", weight: 3 }],
    moods: ["cool", "vibrant", "warm"],
    hueWindows: [[190, 235], [20, 45]],
    personality: ["friendly", "trustworthy", "energetic"],
    patterns: ["waves", "chevron", "concentric"],
    priorityAssets: ["visiting_card", "instagram_post", "flyer", "whatsapp_profile"],
    taglineSeeds: ["Packed and sorted", "Anywhere, arranged", "Trips without the stress"],
    nameRoots: ["Travels", "Tours", "Holidays", "Yatra", "Journeys"],
    voiceHint: "enthusiastic, practical, destination-led",
    packagingHint: "ticket wallets and luggage tags with a bold mark",
    descriptorSeeds: ["Travels & Tours", "Tour Operators", "Since {year}"],
  },

  {
    key: "automotive",
    name: "Auto Garage & Services",
    hint: "Car/bike repair, servicing, spare parts, washing",
    group: "services",
    glyphs: ["car", "gear", "wrench", "bolt"],
    markStyles: [{ value: "glyph", weight: 4 }, { value: "lettermark-cut", weight: 3 }, { value: "monogram", weight: 3 }],
    moods: ["monochrome", "vibrant", "cool"],
    hueWindows: [[0, 30], [200, 230]],
    personality: ["bold", "technical", "trustworthy"],
    patterns: ["diagonal-stripes", "chevron", "grid-dots"],
    priorityAssets: ["signboard", "visiting_card", "invoice", "tshirt"],
    taglineSeeds: ["Fixed properly, first time", "Genuine parts only", "Pick-up and drop, free"],
    nameRoots: ["Motors", "Auto", "Garage", "Works", "Service"],
    voiceHint: "blunt, competence-led, no jargon",
    packagingHint: "durable stickers and oil-resistant labels, one colour",
    descriptorSeeds: ["Auto Care & Service", "Multi-Brand Garage", "Since {year}"],
  },
  {
    key: "mobile_shop",
    name: "Mobile & Electronics",
    hint: "Mobile shop, repairs, accessories, appliances",
    group: "retail",
    glyphs: ["mobile", "bolt", "plug", "spark"],
    markStyles: [{ value: "glyph", weight: 4 }, { value: "lettermark-cut", weight: 3 }, { value: "abstract-stack", weight: 2 }],
    moods: ["vibrant", "cool", "monochrome"],
    hueWindows: [[200, 250], [270, 300]],
    personality: ["modern", "energetic", "friendly"],
    patterns: ["diagonal-stripes", "grid-dots", "chevron"],
    priorityAssets: ["signboard", "visiting_card", "instagram_post", "invoice"],
    taglineSeeds: ["Repairs while you wait", "Every brand, every model", "Best price in {city}"],
    nameRoots: ["Mobiles", "Electronics", "Communications", "Gadgets", "Digital"],
    voiceHint: "fast, price-and-availability led",
    packagingHint: "printed carry bags and warranty cards",
    descriptorSeeds: ["Mobiles & Accessories", "Sales & Service", "Since {year}"],
  },
  {
    key: "hardware",
    name: "Hardware, Paint & Sanitary",
    hint: "Hardware store, paints, plumbing, tiles",
    group: "retail",
    glyphs: ["hammer", "wrench", "gear", "plug", "drop"],
    markStyles: [{ value: "glyph", weight: 4 }, { value: "monogram", weight: 4 }],
    moods: ["vibrant", "earthy", "monochrome"],
    hueWindows: [[10, 45], [200, 240]],
    personality: ["trustworthy", "bold", "technical"],
    patterns: ["chevron", "grid-dots", "diagonal-stripes"],
    priorityAssets: ["signboard", "visiting_card", "invoice", "shopping_bag"],
    taglineSeeds: ["Everything the site needs", "In stock, always", "Contractor rates available"],
    nameRoots: ["Hardware", "Traders", "Sanitary", "Paints", "Enterprises"],
    voiceHint: "practical, stock-and-rate led",
    packagingHint: "sturdy sacks and cartons with a bold single-colour mark",
    descriptorSeeds: ["Hardware & Paints", "Sanitary & Tiles", "Since {year}"],
  },
  {
    key: "furniture",
    name: "Furniture & Interiors",
    hint: "Furniture shop, carpentry, modular kitchens",
    group: "retail",
    glyphs: ["sofa", "house", "lamp", "hammer", "arch-door"],
    markStyles: [{ value: "glyph", weight: 4 }, { value: "monogram", weight: 4 }],
    moods: ["earthy", "monochrome", "jewel"],
    hueWindows: [[20, 45], [90, 130]],
    personality: ["premium", "handcrafted", "modern"],
    patterns: ["lattice", "arches", "grid-dots"],
    priorityAssets: ["signboard", "instagram_post", "visiting_card", "brochure"],
    taglineSeeds: ["Built to be kept", "Made to your measurements", "Wood that lasts a generation"],
    nameRoots: ["Furniture", "Interiors", "Woodworks", "Living", "Studio"],
    voiceHint: "material-led, craft-forward",
    packagingHint: "burned or stamped mark on the timber itself",
    descriptorSeeds: ["Furniture & Interiors", "Modular Interiors", "Since {year}"],
  },
  {
    key: "construction",
    name: "Construction & Contracting",
    hint: "Builder, contractor, civil work, architecture",
    group: "property",
    glyphs: ["hammer", "building", "pillar", "layers", "house"],
    markStyles: [{ value: "abstract-stack", weight: 4 }, { value: "monogram", weight: 4 }, { value: "glyph", weight: 2 }],
    moods: ["monochrome", "earthy", "cool"],
    hueWindows: [[20, 45], [200, 235]],
    personality: ["trustworthy", "technical", "bold"],
    patterns: ["grid-dots", "chevron", "lattice"],
    priorityAssets: ["signboard", "letterhead", "visiting_card", "invoice"],
    taglineSeeds: ["Delivered on schedule", "Built to last", "Quality you can inspect"],
    nameRoots: ["Constructions", "Builders", "Infra", "Developers", "Associates"],
    voiceHint: "solid, delivery-and-quality led",
    packagingHint: "site signage and helmets carrying a bold mark",
    descriptorSeeds: ["Builders & Contractors", "Civil Contractors", "Since {year}"],
  },
  {
    key: "printing",
    name: "Printing & Signage",
    hint: "Print shop, flex banners, stationery, xerox",
    group: "industry",
    glyphs: ["printer", "brush", "layers", "prism"],
    markStyles: [{ value: "glyph", weight: 4 }, { value: "lettermark-cut", weight: 3 }, { value: "abstract-stack", weight: 3 }],
    moods: ["vibrant", "monochrome", "cool"],
    hueWindows: [[0, 360]],
    personality: ["modern", "technical", "energetic"],
    patterns: ["diagonal-stripes", "grid-dots", "chevron"],
    priorityAssets: ["signboard", "visiting_card", "flyer", "invoice"],
    taglineSeeds: ["Same-day printing", "Anything, any size", "Design to delivery"],
    nameRoots: ["Printers", "Graphics", "Print", "Digital", "Signs"],
    voiceHint: "quick, capability-and-turnaround led",
    packagingHint: "its own collateral is the sample — print everything well",
    descriptorSeeds: ["Printers & Signage", "Digital Printing", "Since {year}"],
  },
  {
    key: "logistics",
    name: "Transport & Logistics",
    hint: "Packers and movers, courier, fleet, warehousing",
    group: "industry",
    glyphs: ["truck", "box", "globe", "arrow-up", "compass"],
    markStyles: [{ value: "glyph", weight: 4 }, { value: "abstract-stack", weight: 3 }, { value: "lettermark-cut", weight: 3 }],
    moods: ["vibrant", "cool", "monochrome"],
    hueWindows: [[10, 40], [200, 240]],
    personality: ["bold", "trustworthy", "energetic"],
    patterns: ["chevron", "diagonal-stripes", "grid-dots"],
    priorityAssets: ["signboard", "visiting_card", "invoice", "packaging"],
    taglineSeeds: ["Door to door, on time", "Handled like it's ours", "Tracked, every kilometre"],
    nameRoots: ["Logistics", "Cargo", "Movers", "Transport", "Express"],
    voiceHint: "reliable, time-and-tracking led",
    packagingHint: "large truck-side marks that read at speed",
    descriptorSeeds: ["Packers & Movers", "Transport & Logistics", "Since {year}"],
  },
  {
    key: "solar",
    name: "Solar & Renewable Energy",
    hint: "Solar panels, inverters, green energy",
    group: "industry",
    glyphs: ["solar", "sun-rays", "bolt", "sprout", "plug"],
    markStyles: [{ value: "glyph", weight: 4 }, { value: "abstract-orbit", weight: 3 }, { value: "abstract-stack", weight: 3 }],
    moods: ["vibrant", "cool", "earthy"],
    hueWindows: [[35, 60], [100, 160]],
    personality: ["modern", "technical", "trustworthy"],
    patterns: ["grid-dots", "chevron", "diagonal-stripes"],
    priorityAssets: ["signboard", "visiting_card", "brochure", "website_hero"],
    taglineSeeds: ["Power from your own roof", "Pays for itself", "Clean energy, installed properly"],
    nameRoots: ["Solar", "Energy", "Power", "Urja", "Renewables"],
    voiceHint: "practical, savings-and-payback led",
    packagingHint: "weatherproof panel and inverter labels",
    descriptorSeeds: ["Solar Solutions", "Renewable Energy", "Since {year}"],
  },
  {
    key: "handicraft",
    name: "Handicraft & Home Decor",
    hint: "Handmade goods, pottery, decor, gifting",
    group: "fashion",
    glyphs: ["pot", "loom", "petal", "lotus", "brush"],
    markStyles: [{ value: "glyph", weight: 4 }, { value: "abstract-petal", weight: 3 }, { value: "monogram", weight: 3 }],
    moods: ["earthy", "jewel", "warm"],
    hueWindows: [[15, 45], [140, 180], [340, 360]],
    personality: ["handcrafted", "traditional", "warm"],
    patterns: ["lattice", "arches", "mark-tile"],
    priorityAssets: ["product_label", "packaging", "instagram_post", "shopping_bag"],
    taglineSeeds: ["Made by hand, one at a time", "From the potter's wheel", "Slow made, long kept"],
    nameRoots: ["Crafts", "Kala", "Handmade", "Studio", "Karigari"],
    voiceHint: "story-led, maker-forward, unhurried",
    packagingHint: "recycled board with a hand-stamped mark",
    descriptorSeeds: ["Handmade Crafts", "Home & Decor", "Since {year}"],
  },
  {
    key: "laundry",
    name: "Laundry & Dry Cleaning",
    hint: "Dry cleaner, laundry service, ironing",
    group: "services",
    glyphs: ["fold", "drop", "hanger", "sprout"],
    markStyles: [{ value: "glyph", weight: 4 }, { value: "monogram", weight: 4 }],
    moods: ["cool", "pastel", "monochrome"],
    hueWindows: [[180, 230]],
    personality: ["trustworthy", "friendly", "modern"],
    patterns: ["waves", "grid-dots", "chevron"],
    priorityAssets: ["signboard", "visiting_card", "whatsapp_profile", "invoice"],
    taglineSeeds: ["Back by tomorrow evening", "Pick-up and drop, free", "Handled like your own"],
    nameRoots: ["Laundry", "Dry Cleaners", "Wash", "Fresh", "Care"],
    voiceHint: "prompt, turnaround-led, tidy",
    packagingHint: "garment covers and tags with a clean mark",
    descriptorSeeds: ["Dry Cleaning & Laundry", "Laundry Service", "Since {year}"],
  },
  {
    key: "ngo",
    name: "NGO, Trust & Community",
    hint: "Non-profit, trust, foundation, social work",
    group: "professional",
    glyphs: ["lotus", "sprout", "cross-care", "sun-rays", "petal"],
    markStyles: [{ value: "glyph", weight: 4 }, { value: "abstract-petal", weight: 3 }, { value: "monogram", weight: 3 }],
    moods: ["warm", "earthy", "cool"],
    hueWindows: [[100, 160], [20, 45], [190, 225]],
    personality: ["warm", "trustworthy", "friendly"],
    patterns: ["concentric", "arches", "grid-dots"],
    priorityAssets: ["letterhead", "visiting_card", "poster", "instagram_post"],
    taglineSeeds: ["Small steps, every day", "Work that reaches people", "Since {year}, on the ground"],
    nameRoots: ["Foundation", "Trust", "Seva", "Society", "Initiative"],
    voiceHint: "sincere, work-led, never self-congratulatory",
    packagingHint: "simple recycled collateral, one honest colour",
    descriptorSeeds: ["Charitable Trust", "Foundation", "Since {year}"],
  },
];

/**
 * Typographic defaults per business group.
 *
 * These encode observations about what actually works on Indian high streets
 * and feeds: retail and services need faces that survive a vinyl print read
 * from ten metres, jewellery and property can carry high-contrast serifs
 * because their touchpoints are held in the hand, and creator brands can take
 * risks their customers reward rather than distrust.
 */
const GROUP_TYPE_DEFAULTS: Record<
  IndustryGroup,
  { typeFeels: FontFeel[]; avoidFeels: FontFeel[]; needsSignage: boolean }
> = {
  food: {
    typeFeels: ["rounded", "slab", "humanist", "serif-classic"],
    avoidFeels: ["condensed"],
    needsSignage: true,
  },
  retail: {
    typeFeels: ["rounded", "geometric", "slab", "grotesque"],
    // Delicate moderns disappear on a painted board and in low-res WhatsApp
    // forwards, which is where these businesses are actually seen.
    avoidFeels: ["serif-modern", "serif-classic"],
    needsSignage: true,
  },
  beauty: {
    typeFeels: ["serif-modern", "geometric", "humanist"],
    avoidFeels: ["slab"],
    needsSignage: true,
  },
  fashion: {
    typeFeels: ["serif-modern", "serif-classic", "geometric"],
    avoidFeels: ["rounded", "slab"],
    needsSignage: false,
  },
  services: {
    typeFeels: ["grotesque", "geometric", "slab"],
    avoidFeels: ["serif-classic"],
    needsSignage: true,
  },
  professional: {
    typeFeels: ["grotesque", "geometric", "humanist"],
    avoidFeels: ["rounded"],
    needsSignage: false,
  },
  property: {
    typeFeels: ["serif-modern", "grotesque", "geometric"],
    avoidFeels: ["rounded"],
    needsSignage: true,
  },
  industry: {
    typeFeels: ["grotesque", "condensed", "slab", "geometric"],
    avoidFeels: ["serif-classic", "rounded"],
    needsSignage: true,
  },
  creator: {
    typeFeels: ["geometric", "grotesque", "serif-modern"],
    avoidFeels: [],
    needsSignage: false,
  },
};

/** Applies group defaults to any entry that did not state its own. */
function withTypeDefaults(profile: IndustryProfile): IndustryProfile {
  const defaults = GROUP_TYPE_DEFAULTS[profile.group];
  return {
    ...profile,
    typeFeels: profile.typeFeels ?? defaults.typeFeels,
    avoidFeels: profile.avoidFeels ?? defaults.avoidFeels,
    needsSignage: profile.needsSignage ?? defaults.needsSignage,
  };
}

for (let i = 0; i < INDUSTRIES.length; i++) INDUSTRIES[i] = withTypeDefaults(INDUSTRIES[i]!);

export const INDUSTRY_MAP: Record<string, IndustryProfile> = Object.fromEntries(
  INDUSTRIES.map((i) => [i.key, i]),
);

export function getIndustry(key: string): IndustryProfile {
  return INDUSTRY_MAP[key] ?? INDUSTRY_MAP.startup!;
}

export function industriesByGroup(): { group: IndustryGroup; label: string; items: IndustryProfile[] }[] {
  return INDUSTRY_GROUPS.map((g) => ({
    group: g.key,
    label: g.label,
    items: INDUSTRIES.filter((i) => i.group === g.key),
  })).filter((g) => g.items.length > 0);
}
