import Link from "next/link";
import { Badge, Button, Card, SvgFrame } from "@/components/ui";
import { Wordmark } from "@/components/marketing/Wordmark";
import { SiteHeader, SiteFooter } from "@/components/marketing/Chrome";
import { assetShowcase, marketingSamples } from "@/lib/marketing/samples";
import { LANGUAGE_LIST } from "@/lib/brand/languages";
import { INDUSTRIES } from "@/lib/brand/industries";
import { ASSET_LIST } from "@/lib/render/assets/definitions";
import { getSession } from "@/lib/auth/session";
import { providerLabel } from "@/lib/ai";

export const dynamic = "force-dynamic";

export default async function LandingPage() {
  const session = await getSession().catch(() => null);
  const samples = marketingSamples();
  const hero = samples[0]!;
  const showcase = assetShowcase([
    "visiting_card",
    "instagram_post",
    "signboard",
    "shopping_bag",
    "letterhead",
    "instagram_story",
  ]);
  const ai = providerLabel();

  return (
    <>
      <SiteHeader session={session} />

      <main id="main">
        {/* ---------------------------------------------------------------- */}
        {/* Hero                                                             */}
        {/* ---------------------------------------------------------------- */}
        <section className="px-5 pt-14 pb-20 sm:pt-20 sm:pb-28">
          <div className="max-w-6xl mx-auto grid lg:grid-cols-[1.05fr_0.95fr] gap-12 lg:gap-16 items-center">
            <div className="animate-in-up">
              <Badge tone="brand" className="mb-5">
                Built for Indian business
              </Badge>

              <h1 className="text-[42px] leading-[1.04] sm:text-[58px] lg:text-[64px] font-semibold tracking-[-0.03em]">
                Build a brand,
                <br />
                <span className="text-brand-500">not just a logo.</span>
              </h1>

              <p className="mt-6 text-[17px] sm:text-[19px] text-ink-soft leading-relaxed max-w-xl">
                Create your logo, identity and complete brand kit with AI — built for modern
                Indian businesses.
              </p>

              <div className="mt-8 flex flex-col sm:flex-row gap-3">
                <Link href={session ? "/create" : "/signup"}>
                  <Button size="lg" variant="secondary" full className="sm:w-auto">
                    Create My Brand
                  </Button>
                </Link>
                <Link href="/showcase">
                  <Button size="lg" variant="outline" full className="sm:w-auto">
                    Explore Brands
                  </Button>
                </Link>
              </div>

              <p className="mt-5 text-[13px] text-muted">
                Free to start · No card needed · 11 languages
              </p>
            </div>

            {/* The hero preview is genuinely generated, not a screenshot. */}
            <div className="animate-in-up [animation-delay:120ms]">
              <Card className="p-6 sm:p-8 bg-white">
                <div className="flex items-center justify-between mb-6">
                  <span className="text-[11px] uppercase tracking-[0.14em] text-faint font-medium">
                    Generated just now
                  </span>
                  <Badge tone="success">{hero.score}/100</Badge>
                </div>

                <div className="h-52 sm:h-60 flex items-center justify-center">
                  <SvgFrame svg={hero.logo} className="h-full" label={`${hero.name} logo`} />
                </div>

                <div className="mt-6 pt-5 border-t border-line-soft flex items-center justify-between gap-4">
                  <div className="flex gap-1.5">
                    {[hero.palette.primary, hero.palette.accent, hero.palette.ink].map((hex) => (
                      <span
                        key={hex}
                        className="w-7 h-7 rounded-[7px] border border-ink/8"
                        style={{ background: hex }}
                        title={hex.toUpperCase()}
                      />
                    ))}
                  </div>
                  <div className="text-right">
                    <p className="text-[12px] text-ink font-medium">{hero.fonts.display}</p>
                    <p className="text-[11px] text-muted">{hero.fonts.body}</p>
                  </div>
                </div>
              </Card>
            </div>
          </div>
        </section>

        {/* ---------------------------------------------------------------- */}
        {/* Sample strip                                                     */}
        {/* ---------------------------------------------------------------- */}
        <section className="px-5 py-16 border-y border-line bg-white">
          <div className="max-w-6xl mx-auto">
            <p className="text-center text-[13px] text-muted mb-10">
              Every logo below was generated by the engine on this page load — not drawn by hand.
            </p>
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
              {samples.map((sample) => (
                <div key={sample.name} className="group">
                  <div className="aspect-square rounded-[12px] border border-line bg-paper flex items-center justify-center p-4 transition-all group-hover:border-ink/20 group-hover:shadow-card">
                    <SvgFrame svg={sample.icon} className="h-full w-full" label={sample.name} />
                  </div>
                  <p className="mt-2.5 text-[13px] font-medium text-ink truncate">{sample.name}</p>
                  <p className="text-[11.5px] text-muted truncate">{sample.city}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ---------------------------------------------------------------- */}
        {/* One system                                                       */}
        {/* ---------------------------------------------------------------- */}
        <section className="px-5 py-20 sm:py-28">
          <div className="max-w-6xl mx-auto">
            <div className="max-w-2xl">
              <h2 className="text-[32px] sm:text-[40px] font-semibold tracking-[-0.025em] leading-[1.1]">
                One decision. Then every asset follows.
              </h2>
              <p className="mt-4 text-[16px] sm:text-[17px] text-ink-soft leading-relaxed">
                Most tools give you a logo and leave you to figure out the rest. Chhaap generates a
                brand <em>system</em> — and every card, post and signboard is rendered from that
                same system, so nothing drifts.
              </p>
            </div>

            <div className="mt-12 grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
              {showcase.items.map((item) => (
                <Card key={item.kind} className="overflow-hidden" interactive>
                  <div
                    className="bg-paper-alt border-b border-line-soft overflow-hidden"
                    style={{ aspectRatio: item.ratio }}
                  >
                    <SvgFrame svg={item.svg} contain={false} label={item.label} />
                  </div>
                  <p className="px-4 py-3 text-[13px] font-medium text-ink">{item.label}</p>
                </Card>
              ))}
            </div>

            <p className="mt-8 text-[14px] text-muted">
              …and {ASSET_LIST.length - showcase.items.length} more, from GST invoices to packaging
              and t-shirt prints.
            </p>
          </div>
        </section>

        {/* ---------------------------------------------------------------- */}
        {/* Brand Brain                                                      */}
        {/* ---------------------------------------------------------------- */}
        <section className="px-5 py-20 sm:py-28 bg-ink text-white">
          <div className="max-w-6xl mx-auto">
            <div className="max-w-2xl">
              <Badge className="mb-5 bg-white/10 text-white border-white/15">The Brand Brain</Badge>
              <h2 className="text-[32px] sm:text-[40px] font-semibold tracking-[-0.025em] leading-[1.1] text-white">
                It reasons about your business, not just your name.
              </h2>
              <p className="mt-4 text-[16px] sm:text-[17px] text-white/70 leading-relaxed">
                A kirana store and a jewellery house need different colours, different type and
                different marks. The engine knows the difference — and it checks its own work.
              </p>
            </div>

            <div className="mt-12 grid sm:grid-cols-2 lg:grid-cols-4 gap-5">
              {[
                {
                  title: "Colour with a reason",
                  body: "Palettes are constructed from colour psychology and your category, then contrast-corrected to WCAG before you ever see them.",
                },
                {
                  title: "Type that survives print",
                  body: "Pairings are scored against your personality, then filtered for what actually reproduces in vinyl, embroidery and newsprint.",
                },
                {
                  title: "Marks built to shrink",
                  body: "Every symbol is checked at favicon size and in pure black and white, because that is where weak logos fall apart.",
                },
                {
                  title: "Words in your language",
                  body: "Taglines, captions and WhatsApp greetings written natively in 11 Indian languages — not translated from English.",
                },
              ].map((item) => (
                <div key={item.title} className="border-t border-white/15 pt-5">
                  <h3 className="text-[15px] font-semibold text-white">{item.title}</h3>
                  <p className="mt-2 text-[13.5px] text-white/60 leading-relaxed">{item.body}</p>
                </div>
              ))}
            </div>

            <div className="mt-12 p-6 rounded-[14px] bg-white/5 border border-white/10">
              <p className="text-[13px] text-white/50 mb-1">Generation engine</p>
              <p className="text-[15px] text-white font-medium">{ai.label}</p>
              <p className="text-[13px] text-white/60 mt-2 leading-relaxed max-w-2xl">
                {ai.modelBacked
                  ? "A language model writes the copy; the visual system stays deterministic, so your logo never changes shape between page loads."
                  : "Every visual decision is deterministic and reproducible — no external API, no per-generation cost, and your brand renders identically every time. Add an API key to layer a language model over the copy."}
              </p>
            </div>
          </div>
        </section>

        {/* ---------------------------------------------------------------- */}
        {/* Built for Indian business                                        */}
        {/* ---------------------------------------------------------------- */}
        <section className="px-5 py-20 sm:py-28">
          <div className="max-w-6xl mx-auto">
            <h2 className="text-[32px] sm:text-[40px] font-semibold tracking-[-0.025em] leading-[1.1] max-w-2xl">
              Built for Indian business
            </h2>
            <p className="mt-4 text-[16px] text-ink-soft max-w-2xl leading-relaxed">
              Right print sizes, right languages, right categories. A 89 × 51 mm visiting card, not
              a US 3.5 × 2 inch one.
            </p>

            <div className="mt-12 grid lg:grid-cols-2 gap-10">
              <div>
                <h3 className="text-[13px] uppercase tracking-[0.12em] text-faint font-semibold mb-4">
                  {INDUSTRIES.length} categories
                </h3>
                <div className="flex flex-wrap gap-2">
                  {INDUSTRIES.map((industry) => (
                    <span
                      key={industry.key}
                      className="px-3 h-8 inline-flex items-center rounded-full bg-white border border-line text-[13px] text-ink-soft"
                    >
                      {industry.name}
                    </span>
                  ))}
                </div>
              </div>

              <div>
                <h3 className="text-[13px] uppercase tracking-[0.12em] text-faint font-semibold mb-4">
                  {LANGUAGE_LIST.length} languages
                </h3>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                  {LANGUAGE_LIST.map((language) => (
                    <div
                      key={language.code}
                      className="px-3 py-2.5 rounded-[10px] bg-white border border-line"
                    >
                      <p className="text-[15px] text-ink leading-tight">{language.nativeName}</p>
                      <p className="text-[11.5px] text-muted mt-0.5">{language.name}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ---------------------------------------------------------------- */}
        {/* Readiness score                                                  */}
        {/* ---------------------------------------------------------------- */}
        <section className="px-5 py-20 sm:py-28 bg-white border-y border-line">
          <div className="max-w-6xl mx-auto grid lg:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="text-[32px] sm:text-[40px] font-semibold tracking-[-0.025em] leading-[1.1]">
                It tells you when your logo isn&rsquo;t good enough.
              </h2>
              <p className="mt-4 text-[16px] text-ink-soft leading-relaxed">
                Before you can export, Chhaap runs eight real checks — contrast ratios, greyscale
                separation, stroke weight at favicon size, tracking limits for your script. Each
                failure comes with the specific fix.
              </p>
              <Link href="/signup" className="inline-block mt-7">
                <Button size="lg" variant="secondary">
                  Check my brand
                </Button>
              </Link>
            </div>

            <Card className="p-6">
              <div className="flex items-baseline justify-between mb-5">
                <span className="text-[13px] font-medium text-muted">Brand Readiness</span>
                <span className="text-[32px] font-semibold text-ink tabular-nums">
                  {hero.score}
                  <span className="text-[16px] text-faint">/100</span>
                </span>
              </div>
              <div className="space-y-3">
                {[
                  ["Readable on light backgrounds", "pass"],
                  ["Works in black and white", "pass"],
                  ["Holds up at small sizes", "pass"],
                  ["Suitable for printing and signage", "warn"],
                  ["Typography is consistent", "pass"],
                ].map(([label, status]) => (
                  <div key={label} className="flex items-center gap-2.5 text-[13.5px]">
                    <span
                      className={
                        status === "pass"
                          ? "text-success font-semibold"
                          : "text-warn font-semibold"
                      }
                      aria-hidden="true"
                    >
                      {status === "pass" ? "✓" : "!"}
                    </span>
                    <span className="text-ink-soft">{label}</span>
                  </div>
                ))}
              </div>
            </Card>
          </div>
        </section>

        {/* ---------------------------------------------------------------- */}
        {/* CTA                                                              */}
        {/* ---------------------------------------------------------------- */}
        <section className="px-5 py-24 sm:py-32">
          <div className="max-w-3xl mx-auto text-center">
            <Wordmark size={40} href={null} showText={false} />
            <h2 className="mt-6 text-[34px] sm:text-[46px] font-semibold tracking-[-0.03em] leading-[1.08]">
              From &ldquo;I have an idea&rdquo; to a brand you can open with.
            </h2>
            <p className="mt-5 text-[17px] text-ink-soft leading-relaxed">
              In the time it takes to finish a cup of chai.
            </p>
            <div className="mt-9 flex flex-col sm:flex-row gap-3 justify-center">
              <Link href={session ? "/create" : "/signup"}>
                <Button size="lg" variant="secondary" full className="sm:w-auto">
                  Create My Brand
                </Button>
              </Link>
              <Link href="/pricing">
                <Button size="lg" variant="outline" full className="sm:w-auto">
                  See pricing
                </Button>
              </Link>
            </div>
          </div>
        </section>
      </main>

      <SiteFooter />
    </>
  );
}
