import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Generates the field defaults the Blob adapter needs.
 *
 * PostgreSQL applies `@default(...)` itself; the Blob store has no schema, so
 * without this a created record simply lacks those fields — and the failure is
 * remote from the cause. `session.lastActiveAt` came back undefined and threw
 * inside getSession, which presented as "something went wrong" on every
 * authenticated request.
 *
 * Deriving this from schema.prisma rather than hand-listing it means a new
 * column with a default cannot silently go missing: re-run and it appears.
 */

const root = join(import.meta.dirname, "..");
const schema = readFileSync(join(root, "prisma", "schema.prisma"), "utf8");

type Default = { kind: "now" } | { kind: "value"; value: unknown };

/**
 * Reads the argument of `@default(...)`, balancing parentheses.
 *
 * A naive `\(([^)]*)\)` stops at the first close paren, so `@default(now())`
 * yields `now(` and every timestamp default is silently dropped — which is the
 * bug that made this file necessary in the first place.
 */
function extractDefault(rest: string): string | null {
  const start = rest.indexOf("@default(");
  if (start === -1) return null;

  let depth = 0;
  const from = start + "@default(".length;
  for (let i = from - 1; i < rest.length; i++) {
    if (rest[i] === "(") depth++;
    else if (rest[i] === ")") {
      depth--;
      if (depth === 0) return rest.slice(from, i).trim();
    }
  }
  return null;
}

const models: Record<string, Record<string, Default>> = {};

let current: string | null = null;
for (const raw of schema.split("\n")) {
  const line = raw.trim();

  const modelStart = /^model\s+(\w+)\s*\{/.exec(line);
  if (modelStart) {
    current = modelStart[1]!;
    models[current] = {};
    continue;
  }
  if (line === "}") {
    current = null;
    continue;
  }
  if (!current || line.startsWith("//") || line.startsWith("@@")) continue;

  const field = /^(\w+)\s+(\w+)(\[\])?(\?)?\s*(.*)$/.exec(line);
  if (!field) continue;

  const [, name, type, , optional, rest] = field;
  const expr = extractDefault(rest ?? "");
  if (expr === null) continue;

  // Ids are generated by the adapter itself; skip them here.
  if (/^(cuid|uuid|autoincrement)\(\)$/.test(expr)) continue;

  if (expr === "now()") {
    models[current]![name!] = { kind: "now" };
    continue;
  }

  let value: unknown;
  if (expr === "true" || expr === "false") value = expr === "true";
  else if (/^-?\d+(\.\d+)?$/.test(expr)) value = Number(expr);
  else if (/^".*"$/.test(expr)) value = expr.slice(1, -1);
  else continue; // dbgenerated() and friends have no meaning here

  models[current]![name!] = { kind: "value", value };

  // Optional columns with no default still need to exist as null, or reads of
  // them are `undefined` rather than `null` and strict checks misbehave.
  void optional;
  void type;
}

// Nullable columns without defaults, so records have a complete shape.
const nullable: Record<string, string[]> = {};
current = null;
for (const raw of schema.split("\n")) {
  const line = raw.trim();
  const modelStart = /^model\s+(\w+)\s*\{/.exec(line);
  if (modelStart) { current = modelStart[1]!; nullable[current] = []; continue; }
  if (line === "}") { current = null; continue; }
  if (!current || line.startsWith("//") || line.startsWith("@@")) continue;

  const field = /^(\w+)\s+(\w+)(\[\])?\?\s*(.*)$/.exec(line);
  if (!field) continue;
  const [, name, , isList, rest] = field;
  if (isList) continue;
  if (/@relation/.test(rest ?? "")) continue;
  if (models[current]?.[name!]) continue;
  nullable[current]!.push(name!);
}

const body = `// GENERATED by scripts/gen-defaults.ts — do not edit.
// Run \`npm run gen:defaults\` after changing prisma/schema.prisma.

export type FieldDefault = { kind: "now" } | { kind: "value"; value: unknown };

/** @default(...) values per model, excluding generated ids. */
export const MODEL_DEFAULTS: Record<string, Record<string, FieldDefault>> = ${JSON.stringify(
  Object.fromEntries(Object.entries(models).filter(([, f]) => Object.keys(f).length)),
  null,
  2,
)};

/** Optional columns with no default; materialised as null. */
export const MODEL_NULLABLE: Record<string, string[]> = ${JSON.stringify(
  Object.fromEntries(Object.entries(nullable).filter(([, f]) => f.length)),
  null,
  2,
)};
`;

writeFileSync(join(root, "src", "lib", "store", "defaults.ts"), body, "utf8");

const count = Object.values(models).reduce((n, f) => n + Object.keys(f).length, 0);
console.log(`✓ src/lib/store/defaults.ts — ${count} defaults across ${Object.keys(models).length} models`);
